// <auto-generated />
using System;
using FollowTheMoney.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FollowTheMoney.Migrations
{
    [DbContext(typeof(FollowTheMoneyDbContext))]
    [Migration("20260203040947_fixmodels")]
    partial class fixmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FollowTheMoney.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitteeChamber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitteeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitteeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitteeType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentMembers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ServiceEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ServiceStart")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SourceDocument")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalMembers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("FollowTheMoney.Models.CommitteeMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MembershipEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleInCommittee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.HasIndex("PoliticianId");

                    b.ToTable("CommitteeMemberships");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("DonationTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinancialYear")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DonorCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonorDesciption")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalDonationsMade")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalDonationsReceived")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Electorate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectorateAddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectorateAddress2")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectorateCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElectorateFax")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoratePostalAddress1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoratePostalAddress2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoratePostalPostcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoratePostalState")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoratePostalSuburb")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoratePostcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectorateState")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectorateSuburb")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectorateTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectorateTollFree")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Electorates");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Declared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("currency")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("FollowTheMoney.Models.GovOrg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ABN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnualReport")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditoOtherInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Auditor")
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageStaffingLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardCommitteeAppointedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardCommitteeAppointedByMoreInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("BudgetDocumentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDissolved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEstablished")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstablishedByOrUnder")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstablishedByOrUnderMoreInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("GFSFunctionSector")
                        .HasColumnType("TEXT");

                    b.Property<string>("GFSSectorClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("HasPaidMembers")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficePostcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficeState")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficeStreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficeSuburb")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalDocId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsPortfolioDept")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Materiality")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxBoardMembers")
                        .HasColumnType("TEXT");

                    b.Property<string>("PSActBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentBoardNonBoardTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentOrganisation")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioName")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SourceDocument")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategicCorporateOrganisationalPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalAppropriation")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalDeptExpenses")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfBody")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("GovOrgs");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.OrganisationPoliticalParty", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganisationId", "PoliticalPartyId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("OrganisationPoliticalParties");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DissolvedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartyCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PoliticalParties");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalPartyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MembershipEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MembershipStartDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleInParty")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("PoliticianId");

                    b.ToTable("PoliticalPartyMemberships");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ElectorateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Honorific")
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinisterialTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParliamentaryTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliticalParty")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostNominals")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salutation")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElectorateId");

                    b.ToTable("Politicians");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticianDonation", b =>
                {
                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("TEXT");

                    b.HasKey("PoliticianId", "DonationId");

                    b.HasIndex("DonationId");

                    b.ToTable("PoliticianDonations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisposalDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Asset", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Assets")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.CommitteeMembership", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Committee", "Committee")
                        .WithMany("Memberships")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("CommitteeMemberships")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Committee");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donation", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Donor", "Donor")
                        .WithMany("Donations")
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Organisation", "Organisation")
                        .WithMany("Donations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Organisation");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Gift", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Gifts")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.GovOrg", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.OrganisationPoliticalParty", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Organisation", "Organisation")
                        .WithMany("OrganisationPoliticalParties")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany()
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalPartyMembership", b =>
                {
                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("Memberships")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("PartyMemberships")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliticalParty");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Electorate", "ElectorateRef")
                        .WithMany("Politicians")
                        .HasForeignKey("ElectorateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ElectorateRef");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticianDonation", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Donation", "Donation")
                        .WithMany()
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Stock", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Stocks")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Committee", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donor", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Electorate", b =>
                {
                    b.Navigation("Politicians");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Organisation", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("OrganisationPoliticalParties");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalParty", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("CommitteeMemberships");

                    b.Navigation("Gifts");

                    b.Navigation("PartyMemberships");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
