// <auto-generated />
using System;
using FollowTheMoney.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FollowTheMoney.Migrations
{
    [DbContext(typeof(FollowTheMoneyDbContext))]
    [Migration("20260124182541_AddAusGovOrgModel")]
    partial class AddAusGovOrgModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FollowTheMoney.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinancialYear")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedValue")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("FollowTheMoney.Models.GovOrg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ABN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnnualReport")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditoOtherInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Auditor")
                        .HasColumnType("TEXT");

                    b.Property<string>("AverageStaffingLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardCommitteeAppointedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardCommitteeAppointedByMoreInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("BudgetDocumentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDissolved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEstablished")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstablishedByOrUnder")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstablishedByOrUnderMoreInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("GFSFunctionSector")
                        .HasColumnType("TEXT");

                    b.Property<string>("GFSSectorClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("HasPaidMembers")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficePostcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficeState")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficeStreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadOfficeSuburb")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalDocId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsPortfolioDept")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Materiality")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxBoardMembers")
                        .HasColumnType("TEXT");

                    b.Property<string>("PSActBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentBoardNonBoardTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentOrganisation")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortfolioName")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SourceDocument")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategicCorporateOrganisationalPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalAppropriation")
                        .HasColumnType("TEXT");

                    b.Property<string>("TotalDeptExpenses")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeOfBody")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("GovOrgs");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.OrganisationPoliticalParty", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganisationId", "PoliticalPartyId");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("OrganisationPoliticalParties");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PoliticalParties");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoralDivision")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticalPartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TermEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TermStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Politicians");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticianDonation", b =>
                {
                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("TEXT");

                    b.HasKey("PoliticianId", "DonationId");

                    b.HasIndex("DonationId");

                    b.ToTable("PoliticianDonations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticianOrganisation", b =>
                {
                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("TEXT");

                    b.HasKey("PoliticianId", "OrganisationId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("PoliticianOrganisations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisposalDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PoliticianId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Asset", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Assets")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donation", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Organisation", "Organisation")
                        .WithMany("Donations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("Donations")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Gift", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Gifts")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.GovOrg", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.OrganisationPoliticalParty", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Organisation", "Organisation")
                        .WithMany("OrganisationPoliticalParties")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("OrganisationPoliticalParties")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("Politicians")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticianDonation", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Donation", "Donation")
                        .WithMany("PoliticianDonations")
                        .HasForeignKey("DonationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("PoliticianDonations")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticianOrganisation", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Organisation", "Organisation")
                        .WithMany("PoliticianOrganisations")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("PoliticianOrganisations")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Stock", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Stocks")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donation", b =>
                {
                    b.Navigation("PoliticianDonations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Organisation", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("OrganisationPoliticalParties");

                    b.Navigation("PoliticianOrganisations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalParty", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("OrganisationPoliticalParties");

                    b.Navigation("Politicians");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Gifts");

                    b.Navigation("PoliticianDonations");

                    b.Navigation("PoliticianOrganisations");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
