// <auto-generated />
using System;
using FollowTheMoney.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FollowTheMoney.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FollowTheMoney.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DisposalDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliticianId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("DonationsMadeValue")
                        .HasColumnType("REAL");

                    b.Property<double>("DonationsReceivedValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FinancialYear")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PoliticianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("PoliticalPartyId");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalParty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("PoliticalParties");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectoralDivision")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliticalPartyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TermEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TermStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PoliticalPartyId");

                    b.ToTable("Politicians");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DisposalDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoliticianId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("PoliticianId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("OrganisationPolitician", b =>
                {
                    b.Property<int>("OrganisationsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoliticiansId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrganisationsId", "PoliticiansId");

                    b.HasIndex("PoliticiansId");

                    b.ToTable("OrganisationPolitician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Asset", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Assets")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Donation", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Organisation", "Organisation")
                        .WithMany("Donations")
                        .HasForeignKey("OrganisationId");

                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("Donations")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Politician", null)
                        .WithMany("Donations")
                        .HasForeignKey("PoliticianId");

                    b.Navigation("Organisation");

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalParty", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Organisation", null)
                        .WithMany("PoliticalParties")
                        .HasForeignKey("OrganisationId");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.HasOne("FollowTheMoney.Models.PoliticalParty", "PoliticalParty")
                        .WithMany("Politicians")
                        .HasForeignKey("PoliticalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoliticalParty");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Stock", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Politician", "Politician")
                        .WithMany("Stocks")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
                });

            modelBuilder.Entity("OrganisationPolitician", b =>
                {
                    b.HasOne("FollowTheMoney.Models.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FollowTheMoney.Models.Politician", null)
                        .WithMany()
                        .HasForeignKey("PoliticiansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FollowTheMoney.Models.Organisation", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("PoliticalParties");
                });

            modelBuilder.Entity("FollowTheMoney.Models.PoliticalParty", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Politicians");
                });

            modelBuilder.Entity("FollowTheMoney.Models.Politician", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Donations");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
